{{ define "header" }}
// Package {{ pkg }} contains generated code for schema '{{ schema }}'.
package {{ pkg }}

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"fmt"
	"time"
	"slices"

	"github.com/Masterminds/squirrel"
)

{{ end }}
